baseURL = "https://maku.blog/"
relativeurls = true
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsUseClasses = true
languageCode = "ja-jp"
timeZone = "Asia/Tokyo"
title = "まくろぐ"
# googleAnalytics = "UA-63069513-4"
googleAnalytics = "G-V7PSCLD1ML"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.extensions.typographer]
  # 下記の文字は Typographer 機能で変換しない
  enDash = '--'
  leftDoubleQuote = '"'
  rightDoubleQuote = '"'
  leftSingleQuote = "'"
  rightSingleQuote = "'"

[params]
  sidebarLogo = "img/site-logo-sidebar.png"
  image = "img/site-logo.png"
  facebookAppId = "1572235596285254"
  description = "まくの日記や雑多メモ。"
  Author = "まく"
  AmazonId = "maku04-22"
  CustomSearchId = "partner-pub-6317852277883092:6890083468"

[module]
[[module.imports]]
  path = "github.com/maku77/hugo-module-maku-common"
[[module.imports]]
  path = "github.com/maku77/hugo-module-maku-blog"

